### ISSUE TITLE
Show: emacs opens in splitscreen

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/rvo#1]
Edit and Add Working as expected, but show opens emacs with two buffers in splitscreen:

![image](https://cloud.githubusercontent.com/assets/16048976/17294287/2a3c9ef6-57f6-11e6-9f48-f3a6b8fd8911.png)

**Comment by noqqe** [comment]
Haha,

thats a bug. When I started hacking on rvo I just put my vim options hardcoded in the open_pager function. 

https://github.com/noqqe/rvo/blob/61db1841ce25bc2ecee8fbac7ebd1ba610713294/rvo/utils.py#L51

lol'd. Forgot about it. Will fix.

**Comment by noqqe** [comment]
This is also fixed now by the commit applied in #4
