### ISSUE TITLE
Modify: No possibility to remove tags / categories altogether

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/rvo#2]
There is no way to remove all categories / tags once there is one set.

**Comment by noqqe** [comment]
I personally dont  think uncategorized content would be useful. If there is no category in the first place, its empty. If there ever was a category the only usecase i can think of is for reorganizing content to other categories.

Also its difficult for me to imagine a technical solution for this. A "remove categories" command would be useless. 

If you can think of a usecase for this, please reopen the issue :)
