### ISSUE TITLE
Shortids Change

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/rvo#3]
When working with documents, the shortids change. This is bad, since after every edit i have to lookup the id again via the list and i cant just remember the ids for frequently used docs.

`salazaar@puffy:/home/salazaar $ rvo list

```
ID  Title       Cats    Tags    Date
----  ----------  ------  ------  ----------
2  Test        obsd    du df   2016-08-01
1  RVO issues                  2016-08-01

>>> 2 out of 2 result(s).
salazaar@puffy:/home/salazaar $ rvo modify -t none 2
>>> Updated tags to none
>>> Document Test is already stored in plaintext
salazaar@puffy:/home/salazaar $ rvo list

ID  Title       Cats    Tags    Date
----  ----------  ------  ------  ----------
2  RVO issues                  2016-08-01
1  Test        obsd    none    2016-08-01

>>> 2 out of 2 result(s).
```

`

**Comment by noqqe** [comment]
As discussed in IRC - thats intended. IDs change on every `list` command. 

If you have many documents (as I do) shortids are not very short anymore - like 5563.

**Comment by noqqe** [comment]
I will implement a configuration item 

```
shortids = permanent
# or 
shortids = temporary
```

to be able to make all users happy. All two of them. :P

**Comment by noqqe** [comment]
Phew. This is more work then expected. 

@omgwtflaserguns Next time we meet we need to talk. I have a few technical questions :)

**Comment by noqqe** [comment]
not doing this anymore. Not using it anymore
