### ISSUE TITLE
Add: Stdin add with emacs not working

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/rvo#6]
```
    salazaar@puffy:/home/salazaar $ echo foo | rvo add
    emacs: standard input is not a tty
    >>> Error: No content from editor
```

Looks like thats an emacs problem: [Superuser Thread](http://superuser.com/questions/31404/how-to-make-emacs-read-buffer-from-stdin-on-start)

**Comment by noqqe** [comment]
Sorry, i cannot work around this problem as it is so emacs specific.
